### ISSUE TITLE
Incorrect scroll direction while dragging after flick scroll

### ISSUE THREAD

**Issue by jorbascrumps** [jjcapellan/Phaser3-ScrollingCamera#1]
## Steps to reproduce
1. Starting from the top, flick the camera to have it scroll down
1. While the camera is still scrolling on its own, "catch" it and try to scroll in the opposite direction by dragging

## Expected result
The camera should scroll in the desired direction (up)

## Actual result
The camera will continue attempting to scroll in the original flicked direction (down)

**Comment by netgfx** [comment]
Maybe catching it while scrolling should stop the scroll, and then I guess it would be easier (or even work out of the box) to scroll in other direction.

**Comment by jjcapellan** [comment]
Thanks for the info @jorbascrumps . Although a little late  :), now it works as it should.  

You were right @netgfx , part of the problem was not resetting the speed to zero when the pointer is raised. But the real problem is using the average velocity of the pointer  **(endY - startY) / time**, which implies that if a movement is made and then the pointer stops for a while, releasing it still had some speed.  

Thank you both for your help.
Regards.
