### ISSUE TITLE
touch velocity is missing on mobile device?

### ISSUE THREAD

**Issue by crapthings** [jjcapellan/Phaser3-ScrollingCamera#6]
it's working on a desktop device, but not a mobile device

https://streamable.com/dq3v7z

**Comment by jjcapellan** [comment]
Hi @crapthings ,
I'll check it.
Thanks for the info !!

**Comment by jjcapellan** [comment]
Hi @crapthings,
New version 2.0.3 released. 
I have tested the new version on my huawei and the problem seems to be fixed.
The cause of the problem was that when stopping the finger, if the finger was not lifted before the next frame, the speed was set to 0. I have set a longer reaction time, but if you still have problems let me know.
Regards.

**Comment by crapthings** [comment]
2.0.2
https://streamable.com/8hhodc

2.0.3
https://streamable.com/j0z8pf

it works perfectly~
